apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-pv-hostpath
spec:
  storageClassName: localstorage 
  resources:
    requests:
      storage: 1Gi
  accessModes:
    - ReadWriteOnce

