apiVersion: v1
kind: Pod
metadata:
  name: webapp-secret
  labels:   
    app: webapp
spec:
  containers:
  - image: mmumshad/simple-webapp-color
    env:
    - name: APP_COLOR
      valueFrom: 
        configMapKeyRef:
          name: webapp-config
          key: APP_COLOR
    name: webapp-color
    volumeMounts:
    - name: html
      mountPath: /var/htdocs
    ports:
    - containerPort: 80
      protocol: TCP
  volumes:
  - name: html
    emptyDir: {}
  - name: secret
    secret:
      secretName: webapp-secret